---
name: golang
"on": pull_request
permissions:
  contents: read
  packages: read
jobs:
  mcvs-golang-action:
    strategy:
      matrix:
        args:
          - testing-type: component
          - testing-type: coverage
          - testing-type: integration
          - testing-type: lint
            build-tags: component
          - testing-type: lint
            build-tags: e2e
          - testing-type: lint
            build-tags: integration
          - testing-type: lint-commit
          - testing-type: lint-git
          - testing-type: mocks-tidy
          - testing-type: security-golang-modules
          - testing-type: security-grype
          - testing-type: security-trivy
          - testing-type: unit
    runs-on: ubuntu-24.04
    env:
      TASK_X_REMOTE_TASKFILES: 1
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: schubergphilis/mcvs-golang-action@v3.4.1
        env:
          test-timeout: 10m0s
        with:
          build-tags: ${{ matrix.args.build-tags }}
          code-coverage-expected: 24.4
          code-coverage-timeout: ${{ env.test-timeout }}
          golang-unit-tests-exclusions: |-
            \(deprecated\|filesystem\|mocks\|swagger\|cmd\/mcvs-.*\|mcvs-\(chart-designer\|reporter\)\)$\?
          golangci-timeout: 10
          test-timeout: ${{ env.test-timeout }}
          testing-type: ${{ matrix.args.testing-type }}
          token: ${{ secrets.GITHUB_TOKEN }}
